config/routes.rb
Tytc::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # resources :links
  resources :votes

  # TODO: cleanup routes

  # resources :languages do
  #   resources :links
  # end
  get ':language', to: 'languages#show', as: 'language'
  #
  scope ':language', as: 'language' do
    resources :links
  end

  root to: "root#home"
end

app/models/language.rb
# == Schema Information
#
# Table name: languages
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  links_count :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Language < ActiveRecord::Base
  has_many :tags, inverse_of: :language
  has_many :links, through: :tags, order: 'votes_count DESC'

  validates :name, presence: true, uniqueness: { case_sensitive: false }

  before_create :generate_slug

  def generate_slug
    self.slug = self.name.downcase.gsub(/[^\w\-]+/, "-")
  end

  def to_param
    slug
  end
end

app/models/link.rb
# == Schema Information
#
# Table name: links
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  url         :string(255)
#  description :text
#  user_id     :integer
#  votes_count :integer
#  level       :integer
#  free        :boolean
#  created_at  :datetime
#  updated_at  :datetime
#

class Link < ActiveRecord::Base
  attr_accessor :language

  belongs_to :user
  has_many :votes, inverse_of: :link
  has_one :tag, inverse_of: :link
  #TODO this isn't working
  has_one :language, through: :tag

  BEGINNER = 1
  INTERMEDIATE = 2
  ADVANCED = 3

  validates :title, presence: true, uniqueness: { case_sensitive: false }
  validates :url, presence: true, uniqueness: { case_sensitive: false }
  # validates :description, presence: true
  validates :free, inclusion: [true, false]
  validates :level, presence: true
  validates :user, presence: true

  after_create :initial_vote

  def initial_vote
    Vote.create do |v|
      v.link_id = self.id
      v.user_id = self.user_id
    end
  end

  def url_host
    URI.parse(self.url).host.reverse.chomp('.www').reverse
  end


  #TODO Very Bad
  def level_name
    if level == 1
      "Beginner"
    elsif level == 2
      "Intermediate"
    elsif level == 3
      "Advanced"
    end
  end

end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id          :integer          not null, primary key
#  link_id     :integer
#  language_id :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Tag < ActiveRecord::Base
  belongs_to :link, dependent: :destroy
  belongs_to :language, dependent: :destroy

  validates :link, presence: true, uniqueness: { scope: :language_id}
  validates :language, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  username               :string(255)
#  github_id              :integer
#  god                    :boolean
#  created_at             :datetime
#  updated_at             :datetime
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:github]

  has_many :links, inverse_of: :user
  has_many :votes, inverse_of: :user

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :email, uniqueness: { case_sensitive: false }, allow_blank: true, allow_nil: true
  validates :github_id, presence: true, uniqueness: true

  def self.github_find_or_create(auth)
    unless user = User.find_by_github_id(auth['uid'])
      user = create! do |u|
        u.github_id = auth['uid']
        u.avatar_url = auth['info']['image']
        u.username = auth['info']['nickname']
        u.email = auth['info']['email']
        u.password = SecureRandom.hex(6)
      end
    end
    return user
  end

  def is_god?
    god == true
  end

  def voted_on?(link_id)
    votes.where(link_id: link_id).any?
  end


  def email_required?
    false
  end

  def email_changed?
    false
  end

end

app/models/vote.rb
# == Schema Information
#
# Table name: votes
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  link_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Vote < ActiveRecord::Base
  belongs_to :user, dependent: :destroy
  belongs_to :link, dependent: :destroy, counter_cache: true

  validates :user, presence: true, uniqueness: { scope: :link_id}
  validates :link, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from ActionController::RoutingError, :with => :render_404

  private

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end

  def render_404(exception = nil)
    if exception
      # do something
    end

    render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
  end

end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController

  def show
    @language = Language.find_by_slug(params[:language]) || not_found
    @newLink = Link.new
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!, only: :create

  def new
    @language = Language.find_by_slug(params[:language]) || not_found
    @newLink = Link.new
  end

  def show
    @link = Link.find(params[:id])
    @newLink = Link.new

    @language = @link.tag.language
    render '/languages/show'
  end


  def create
    @newLink = current_user.links.build(link_params)
    @language = Language.find(link_params['language'].to_i)

    if @newLink.save

      Tag.create do |t|
        t.link_id = @newLink.id
        t.language_id = @language.id
      end
      flash[:new_link_id] = @newLink.id
      redirect_to language_link_path(@newLink.tag.language, @newLink)
    else
      flash[:error] = @newLink.errors.full_messages.join(", ")
      render 'new'
    end

  end

  private

  def link_params
    params.require(:link).permit(:url, :description, :title, :level, :free, :language, :author)
  end

end

app/controllers/root_controller.rb
class RootController < ApplicationController

  def home
    @languages = Language.all.order('links_count DESC')
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def github
    auth = request.env["omniauth.auth"]
    @user = User.github_find_or_create(auth)
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!

  def create
    @vote = current_user.votes.build(vote_params)

    if @vote.save
      render @vote
    else
      render :text => @vote.errors.full_messages.join(", "), :status => :unprocessable_entity
    end
  end

  private

  def vote_params
    params.require(:vote).permit(:link_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/languages/_language.html.haml
.block-container{:class => "#{language.name}"}
  - if params[:action] == "home"
    .heading
      .sticky
        .container
          .col-sm-offset-5.sticky-language
            = link_to language.name, language_path(language)
      .language-heading-name
        .container
          .col-sm-offset-5
            = link_to language.name, language_path(language)
  .container.links-container
    %ul.col-sm-12.links-ul
      - if params[:action] == "home"
        = render language.links.first(3)
        .see-all
          = link_to language_path(language) do
            %li.link
              .link-container
                .link-head
                  = "See all #{language.name} tutorials"
      - else
        = render language.links

app/views/languages/show.html.haml
= content_for :language_name do
  = @language.name

= render @language
.block-container
  .container.link-container
    .col-sm-12
      - if current_user
        .add-link-button{"data-toggle"=>"modal", "data-target"=>".new-link-form"}
          Add tutorial
      - else
        .add-link-button{"data-toggle"=>"modal", "data-target"=>".login-form"}
          Add tutorial
= render "links/new"

:javascript
  $('.new-link-form').addClass('fade');

app/views/layouts/application.html.haml
!!! XML
!!!
%html{:lang=>'en'}
  %head
    %meta{:charset=>"utf-8"}
    %meta{"http-equiv"=>"X-UA-Compatible", :content=>"IE=edge"}
    %meta{:name=>"viewport", :content=>"width=device-width, initial-scale=1"}
    %title teach yourself to code
    / is open source!
    / check it out https://github.com/kateray/tytc
    = favicon_link_tag 'favicon.ico'
    <meta name = "description" content = "Link sharing site for the best programming tutorials and resources">
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = render "shared/google_analytics"
    = csrf_meta_tag
  %body{:class => "#{controller_name} #{action_name}"}
    -# - if flash[:error]
    -#   = content_tag :div, flash[:error], :class => "alert alert-danger"

    %span.hidden-xs
      %nav.navbar.navbar-default.navbar-fixed-top{:role=>"navigation"}
        .container
          .col-sm-12
            .navbar-header.col-sm-5
              .navbar-brand
                = link_to root_path do
                  %img{:src => asset_path("code-logo.png")}
                  teach yourself to code
            .language-nav.dropdown.col-sm-5
              %btn.dropdown-toggle{type: "button", id: "language-dropdown", "data-toggle"=> "dropdown"}
                .language-name
                  = yield :language_name
                %i.fa.fa-sort
              %ul.dropdown-menu{role: "menu", "aria-labelledby"=>"language-dropdown"}
                - Language.all.each do |l|
                  %li
                    = link_to l.name, language_path(l), html_options: {role: "menuitem", tabindex: "-1"}

            .nav.navbar-nav.navbar-right
              = link_to('about', '#about')
              |
              - if current_user
                = image_tag(current_user.avatar_url, class: "avatar")
                = link_to('sign out', destroy_user_session_path, :method => :delete)
              - else
                %span.login-link{"data-toggle"=>"modal", "data-target"=>".login-form"}
                  sign in

    %span.visible-xs
      %nav.navbar.navbar-default.navbar-fixed-top{:role=>"navigation"}
        .navbar-header
          %a.navbar-brand{:href => "/"}
            %img.hidden-xs{:src => asset_path("code-logo.png")}
            teach yourself to code
            .language-name
              = yield :language_name
          .mobile-right
            = link_to('about', '#about')


    = yield
    = render "/shared/login"
    .block-container.special-footer
      .sticky
        .container
          .col-sm-offset-5.sticky-language
            everything
      .footer#about
        .container
          .col-sm-12
            #footer-header
              about
              %br
              %br
            Four years ago, a friend lent me his Rails book and I took it with me on a family vacation and learned Rails. I was happy to discover that programming itself was fun, but also realized it was power. Anything I could imagine, I could build. Suddenly I was having new ideas about every problem I encountered, and the ability to act on them. It changed the way I thought.
            %br
            %br
            <a href="http://techcrunch.com/2014/05/24/dont-believe-anyone-who-tells-you-learning-to-code-is-easy">Don’t believe people who say that learning to code is easy.</a> Better to go in knowing that it’s hard and frustrating and that most of the time you will feel like you <a href="http://i.imgur.com/xVyoSl.jpg" target="_blank">have no idea what you’re doing</a>. There are a lot of people who will help you, at <a href="http://www.meetup.com" target="_blank">Meetups</a> or on <a href="http://stackoverflow.com" target="_blank">StackOverflow</a>. But if you don’t know where to start, I made this site for you.
            %br
            Have fun.
            %br
            #signoff
              <3 @<a href="https://twitter.com/kraykray" target="_blank">kraykray</a>
            %br
            %br
              Source code available on <a href="https://github.com/kateray/tytc" target="_blank">Github</a>
            %br
            %br
            %i
              Huge thanks to <a href="https://twitter.com/codybrown" target="_blank">Cody Brown</a> and <a href="https://twitter.com/aidanfeldman" target="_blank">Aidan Feldman</a> for their help with the design and content of this site, and to the <a href="http://www.shuttleworthfoundation.org" target="_blank">Shuttleworth Foundation</a> for their awesome Flash Grant.
            %a{href: "http://www.shuttleworthfoundation.org", target: "_blank"}
              %img{:src => asset_path("shuttleworth.jpg")}

app/views/links/_link.html.haml
%li.link{"data-id" => link.id, "data-url" => language_link_path(link.tag.language, link), class: ('new-link' if flash[:new_link_id] == link.id) }
  .link-container
    .link-head
      %span.link-title
        = link.title
        .link-author
          - if !link.author.blank?
            = link.author
            |
          = link.url_host
      .link-metadata
        - if !link.free
          %span.free-tag
            $
        %span.level-tag{class: link.level_name}
          = link.level_name
        %span.votes-count
          %span.user-votes
            - if current_user
              - if current_user.voted_on?(link.id)
                %i.vote-icon.voted.fa.fa-heart
              - else
                %i.vote-icon.vote-button.fa.fa-heart
            - else
              %i.vote-icon.fa.fa-heart{"data-toggle"=>"modal", "data-target"=>".login-form"}
            = render link.votes

    .link-expanded.collapse
      .link-description
        = link.description
        %span.link-author
          = "- "
          = link_to "@#{link.user.username}", "http://github.com/#{link.user.username}", :target=>"_blank"
      = link_to "Start Tutorial ->", link.url, :target=>"_blank", :class=> "link-url"
      %div{:style=>"clear:both"}

app/views/links/_new.html.haml
.modal.new-link-form{"aria-hidden" => "true", "aria-labelledby" => "myLargeModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        Add a new link
        %button{type:"button", class:"close", "data-dismiss"=>"modal", "aria-hidden"=>"true"} &times;
      .modal-body.container-fluid
        = form_for [@language, @newLink], html: {class: "form-horizontal", role: "form"} do |f|
          = f.hidden_field :language, value: @language.id
          .form-group
            = f.label :title, "Title"
            = f.text_field :title, autocomplete: "off"
          .form-group
            = f.label :url, "URL"
            = f.text_field :url, value: "http://", type: "url", autocomplete: "off"
          .form-group
            = f.label :author, "Author (optional)"
            = f.text_field :author, autocomplete: "off"
          .form-group
            = f.label :description, "What did you like about it? (optional)"
            .row
              = f.text_area :description
          .row
            = f.label :level, "Who's it for?"
            .btn-group{"data-toggle"=>"buttons"}
              .btn.btn-primary
                = f.radio_button :level, 1
                Beginner
              .btn.btn-primary
                = f.radio_button :level, 2
                Intermediate
              .btn.btn-primary
                = f.radio_button :level, 3
                Advanced
          .row
            = f.label :free, "Is it free?"
            .btn-group{"data-toggle"=>"buttons"}
              .btn.btn-primary
                = f.radio_button :free, true
                Yes
              .btn.btn-primary
                = f.radio_button :free, false
                No
          .row
            = f.submit "Submit", class: 'submit-link'

app/views/links/index.html.haml
.row
  .front-splash
    .container
      .message
        the best way to learn to code is to make something you didn't know you could.
= render @languages

app/views/links/new.html.haml
= render @language
= render "links/new"

:javascript
  $('.new-link-form').modal('show');

app/views/root/home.html.haml
= content_for :language_name do
  &nbsp

.front-splash
  .container
    .message
      It takes work.
    .small-message
      %i.fa.fa-star
      Top tutorials, recommended by programmers
= render @languages

app/views/shared/_login.html.haml
.modal.fade.login-form{"aria-hidden" => "true", "aria-labelledby" => "myLargeModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        Sign in
        %button{type:"button", class:"close", "data-dismiss"=>"modal", "aria-hidden"=>"true"} &times;
      .modal-body.container-fluid
        Sign in with
        = link_to "GitHub", user_omniauth_authorize_path(:github)
        %br
        %a{href: user_omniauth_authorize_path(:github)}
          .login-with-github
        -# = link_to image_tag("github-round.png"), user_omniauth_authorize_path(:github)
        .explanation
          Don't know GitHub? It's a code-sharing site, and a good first step to programming.
          = link_to "Create an account", "https://github.com", target: "_blank"

app/views/votes/_vote.html.haml
= link_to "http://github.com/#{vote.user.username}", :target=>"_blank" do
  = image_tag(vote.user.avatar_url, class: "avatar")